[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[profile.deploy]
optimizer = true
optimizer_runs = 999999

[fmt]
sort_imports = true
wrap_comments = true

[dependencies]
forge-std = "1.9.4"
solady = "0.0.267"
